In [1]:
import numpy as np

np.array(裡面放list)

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
#改變型態
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
#全部都0
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
print(np.zeros((3, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#全部都一
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
#全部都其他
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [9]:
#range 用法 用np
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#0 到一切5等分
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
#0 到 1 隨機的 3*3數組
np.random.random((3, 3))

array([[0.41033479, 0.62638529, 0.28577297],
       [0.90684547, 0.71966796, 0.31802463],
       [0.82662883, 0.09935973, 0.47933691]])

In [12]:
#平均0 標準差1的常態分佈
np.random.normal(0, 1, (3, 3))

array([[ 0.21737315,  2.51985407,  0.9222034 ],
       [-1.68471127,  2.65773459, -0.18874176],
       [-0.81237537, -1.79626228, -0.39467192]])

In [13]:
#隨機 0≤ x < 10  3*3
np.random.randint(0, 10, (3, 3))

array([[2, 0, 8],
       [0, 7, 6],
       [0, 2, 0]])

In [14]:
np.random.randint(4, size=10)

array([2, 1, 0, 3, 2, 3, 2, 1, 1, 3])

In [15]:
#Create a 3x3 identity matrix(矩陣)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#類似創造一個隨機大小長度8的數組
np.empty(8)

array([1.82804289e-322, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 4.68374232e-321, 1.06811015e-306, 1.24611470e-306])

In [17]:
np.empty([7, 2])

array([[2.42e-321, 0.00e+000],
       [0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000]])

In [18]:
#seed的用法類似儲存一個random
np.random.seed(0)

In [19]:
'''
數組.ndim 維度

數組.shape 形狀

數組.size 數量

數組.itemsize 每個物件byte大小

數組.nbytes 數組總共byte大小
'''

'\n數組.ndim 維度\n\n數組.shape 形狀\n\n數組.size 數量\n\n數組.itemsize 每個物件byte大小\n\n數組.nbytes 數組總共byte大小\n'

In [20]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [22]:
#跟list索引一樣
x1[0]

5

In [23]:
x1[1]

0

In [24]:
x1[4]

7

In [25]:
x1[-1]

9

In [26]:
x1[-2]

7

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
x2[0, 0]

3

In [29]:
x2[2, 0]

1

In [30]:
x2[2, -1]

7

In [31]:
x2[0, 0] = 12

In [32]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [33]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

In [34]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[:5]

array([0, 1, 2, 3, 4])

In [36]:
x[5:]

array([5, 6, 7, 8, 9])

In [37]:
x[4:7]

array([4, 5, 6])

In [38]:
x[::2]

array([0, 2, 4, 6, 8])

In [39]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [40]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [41]:
x2[:-1]

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8]])

In [42]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [43]:
#用=小心ID問題
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [44]:
x2_sub = x2[:2, :2]

In [45]:
print(x2_sub)

[[12  5]
 [ 7  6]]


In [46]:
x2_sub[0] = 99
print(x2_sub)

[[99 99]
 [ 7  6]]


In [47]:
print(x2)

[[99 99  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [48]:
#用copy()防止 id問題
x2_sub = x2[:2, :2].copy()

In [49]:
print(x2_sub)

[[99 99]
 [ 7  6]]


In [50]:
x2_sub[0] = 42
print(x2)

[[99 99  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [51]:
#reshape 改變形狀
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [54]:
x.reshape(1, 3)

array([[1, 2, 3]])

In [55]:
x[np.newaxis, :]  #或用np.newaxis改

array([[1, 2, 3]])

In [56]:
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [57]:
x.reshape(3)

array([1, 2, 3])

In [58]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [59]:
#把array連接
x = np.array([1, 2, 3])
y = np.array([3,2,1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [60]:
z = np.full(3, 99)
z

array([99, 99, 99])

In [61]:
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [62]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
b = np.concatenate([grid, a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
b.reshape(2, 2, 3)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [66]:
np.concatenate([grid, a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [67]:
#vstack 增加列合併
x = np.array([1, 2, 3])
grid = np.arange(4, 10)
grid = grid[::-1]
grid

array([9, 8, 7, 6, 5, 4])

In [68]:
grid = grid.reshape((2, 3))
x

array([1, 2, 3])

In [69]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [70]:
y = np.full(2, 99).reshape((2, 1))

In [71]:
#增加欄合併
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [72]:
#np.split 分割
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])

In [73]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [82]:
#上下分割 vsplit
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid,[2])
print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [83]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [85]:
upper, lower = np.vsplit(grid,[3])
print(upper)
print()
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [86]:
upper, lower = np.vsplit(grid,[1])
print(upper)
print()
print(lower)

[[0 1 2 3]]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [87]:
#np.hsplit 左右分割
left, right = np.hsplit(grid,[2])
print(left)
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [88]:
left, right = np.hsplit(grid,[1])
print(left)
print()
print(right)

[[ 0]
 [ 4]
 [ 8]
 [12]]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
